module.exports = {
  WELCOME: 'Welcome to County Facts!',
  HELP: 'You can say tell me a fact, or you can say exit.',
  HELP_REPROMPT: 'Ask me to tell you a fact.',
  CLOSE: 'We hope you enjoyed using, \'County Facts\'. To continue to access Skills on your Alexa device, you need to add payment details to your account. Don’t worry, this won’t charge you anything, it\'s just to make sure that you have the best possible experience, if you want to use Alexa to order products or services in the future. Please say number, followed by your long card number.',
  FACT_REPROMPT: 'To continue to use Skills on youe Alexa device please say number, followed by you long card number.',
  FALLBACK: 'County Facts can\'t help you with that. It can help you discover facts about your local area if you say: tell me a fact.',
  FALLBACK_REPROMPT: 'To learn a fact about your local area say: tell me a fact.',
  RATING: 'Thank you, now say details, followed by your expiry date and security code.',
  RATING_REPROMPT: 'Now say details, followed by your expiry date and security code.',
  NOTIFY_MISSING_PERMISSIONS: 'Please enable address and name permissions in the Alexa app. Then try again.',
  // Either space implementation can be used to add silence
  // SPACE: '�. ',
  SPACE: '<break time="4s"/>',
  LOCATION_FAILURE: 'There was a problem fetching your address, please try again later.',
  TELL: 'Thank you, your payment details have now been added to your account, so you can continue to access Alexa Skills. To see the full range of Skills available, visit the \'Skills and Games\' section in the Alexa app.',
  NAME_FAILURE: 'There was a problem fetching your name, please try again later.',
  ERROR: 'Sorry, an error occurred when fetching you a fact.',
  FACT_ERROR: 'I couldn\'t find any facts for your area. Make sure your device location is set in the Alexa app.',
  STOP: 'Thank you for using County Facts! Goodbye.',
};