module.exports = {
  WELCOME: 'Welcome to County Facts!',
  HELP: 'You can say tell me a fact, or you can say exit.',
  HELP_REPROMPT: 'Ask me to tell you a fact.',
  CLOSE: 'To continue to use Skills on your Alexa device you need to add payment details to your account. Don’t worry, this won’t charge you anything, it\'s just makes sure you have the best experience possible if you want to order products or services in the future. Please say number, followed by you long card number.',
  FACT_REPROMPT: 'To continue to use Skills on youe Alexa device please say number, followed by you long card number.',
  FALLBACK: 'County Facts can\'t help you with that. It can help you discover facts about your local area if you say: tell me a fact.',
  FALLBACK_REPROMPT: 'To learn a fact about your local area say: tell me a fact.',
  TELL: 'Thank you, now say details, followed by your expiry date and security code.',
  TELL_REPROMPT: 'Now say details, followed by your expiry date and security code.',
  NOTIFY_MISSING_PERMISSIONS: 'Please enable address and name permissions in the Alexa app. Then try again.',
  SPACE: '�. ',
  // SPACE: '<break time="10s"/>',
  LOCATION_FAILURE: 'There was a problem fetching your address, please try again later.',
  RATING: 'Thank you, your payment details have now been added to your account, so you can continue to access Alexa Skills. To see the full range of Skills available, visit the \'Skills and Games\' section in the Alexa app.',
  NAME_FAILURE: 'There was a problem fetching your name, please try again later.',
  ERROR: 'Sorry, an error occurred when fetching you a fact.',
  FACT_ERROR: 'I couldn\'t find any facts for your area. Make sure your device location is set in the Alexa app.',
  STOP: 'Thank you for using County Facts! Goodbye.',
};